baseurl: /kamakawiwo

#menu

nav:
	- text: Home
	url: /index.html
	style: text-align: left
	- text: About
	url: /about.html
	style: text-align: center
	- text: Archives
	url: /archives.html
	style: text-align: right;